#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd and makes up a story based on it,
# using the while loop + IFS.

while IFS=':' read -r username password uid gid info homedir shell; do
  echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell."\
  "$uid's place is protected by the passcode $password, more info about the user here: $info"

done < "/etc/passwd"
