#!/usr/bin/env bash
# This script displays:
#     *The content of the current directory
#     *In a list format
#     *Where only the part of the name after the first dash is displayed
# Requirements: You must use the for loop and do not display hidden files.

list=$(ls)
for file in $list;
do
  if [ ! -h "$file" ] && [ -f "$file" ]; 
  then
      echo "$file" | cut -d '-' -f2
  fi
done
