#!/usr/bin/env bash
# Script that turns on an Apache Server on Docker container
# and return a page containing Hello Holberton when querying the root of it

# Apache HTTP Server Installation
apt update
apt install -y apache2

# Apache web content server
cd /var/www/html || exit

# add to index.html file to contain "Hello Holberton"
{
echo "<!DOCTYPE html>"
echo "<html>"
echo "<head>"
echo "    <title>Hello Holberton</title>"
echo "</head>"
echo "<body>"
echo "    <h1>Hello Holberton</h1>"
echo "</body>"
echo "</html>"
} > index.html

# Restart Apache service to apply changes
sudo service apache2 start
